services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: tictactoe-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tictactoe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tictactoe-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/tictactoe
      SERVER_URL: http://localhost:3100
    ports:
      - "3100:3100"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
      - /app/prisma/generated

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tictactoe-frontend
    ports:
      - "5173:4173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist

volumes:
  postgres_data:
